// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventarioSupermercado.Entities
{
    public partial class tbComprasDetalle
    {
        public int Comde_Id { get; set; }
        public int Comen_Id { get; set; }
        public int Produ_Id { get; set; }
        public int Comde_Cantidad { get; set; }
        public int Unida_Id { get; set; }
        public int Comde_UsuarioCreacion { get; set; }
        public DateTime Comde_FechaCreacion { get; set; }
        public int? Comde_UsuarioModificacion { get; set; }
        public DateTime? Comde_FechaModificacion { get; set; }
        public bool? Comde_Estado { get; set; }

        public virtual tbUsuarios Comde_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Comde_UsuarioModificacionNavigation { get; set; }
        public virtual tbComprasEncabezado Comen { get; set; }
        public virtual tbProductos Produ { get; set; }
        public virtual tbUnidades Unida { get; set; }
    }
}