// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventarioSupermercado.Entities
{
    public partial class tbComprasEncabezado
    {
        public tbComprasEncabezado()
        {
            tbComprasDetalle = new HashSet<tbComprasDetalle>();
        }

        public int Comen_Id { get; set; }
        public int Prove_Id { get; set; }
        public int Sucur_Id { get; set; }
        public int Emple_Id { get; set; }
        public DateTime Comen_FechaIngreso { get; set; }
        public int Comen_UsuarioCreacion { get; set; }
        public DateTime Comen_FechaCreacion { get; set; }
        public int? Comen_UsuarioModificacion { get; set; }
        public DateTime? Comen_FechaModificacion { get; set; }
        public bool? Comen_Estado { get; set; }

        public virtual tbUsuarios Comen_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Comen_UsuarioModificacionNavigation { get; set; }
        public virtual tbEmpleados Emple { get; set; }
        public virtual tbProveedores Prove { get; set; }
        public virtual tbSucursales Sucur { get; set; }
        public virtual ICollection<tbComprasDetalle> tbComprasDetalle { get; set; }
    }
}