// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventarioSupermercado.Entities.Entities
{
    public partial class tbMetodosPago 
    {
        public int MtPag_Id { get; set; }
        public string MtPag_Descripcion { get; set; }
    }
}
