// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace InventarioSupermercado.Entities.Entities
{
    public partial class tbProductos
    {
        public tbProductos()
        {
            tbComprasDetalle = new HashSet<tbComprasDetalle>();
            tbVentasDetalle = new HashSet<tbVentasDetalle>();
        }

        public int Produ_Id { get; set; }
        public string Produ_Descripcion { get; set; }
        public int Produ_Existencia { get; set; }
        public int Unida_Id { get; set; }
        public decimal Produ_PrecioCompra { get; set; }
        public decimal Produ_PrecioVenta { get; set; }
        public int Impue_Id { get; set; }
        public int Categ_Id { get; set; }
        public int Prove_Id { get; set; }
        public int Sucur_Id { get; set; }
        public int Produ_UsuarioCreacion { get; set; }
        public DateTime Produ_FechaCreacion { get; set; }
        public int? Produ_UsuarioModificacion { get; set; }
        public DateTime? Produ_FechaModificacion { get; set; }
        public bool? Produ_Estado { get; set; }

        public string Produ_ImagenUrl { get; set; }

        [NotMapped]
        public string Unida_Descripcion { get; set; }
        [NotMapped]
        public string Prove_Marca { get; set; }
        [NotMapped]
        public decimal Impue_Descripcion { get; set; }

        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }
        [NotMapped]
        public string Categ_Descripcion { get; set; }

        [NotMapped]
        public string Sucur_Descripcion { get; set; }


        public virtual tbCategorias Categ { get; set; }
        public virtual tbImpuestos Impue { get; set; }
        public virtual tbUsuarios Produ_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Produ_UsuarioModificacionNavigation { get; set; }
        public virtual tbProveedores Prove { get; set; }
        public virtual tbSucursales Sucur { get; set; }
        public virtual tbUnidades Unida { get; set; }
        public virtual ICollection<tbComprasDetalle> tbComprasDetalle { get; set; }
        public virtual ICollection<tbVentasDetalle> tbVentasDetalle { get; set; }
    }
}