// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InventarioSupermercado.Entities
{
    public partial class tbUnidades
    {
        public tbUnidades()
        {
            tbComprasDetalle = new HashSet<tbComprasDetalle>();
            tbProductos = new HashSet<tbProductos>();
            tbVentasDetalle = new HashSet<tbVentasDetalle>();
        }

        public int Unida_Id { get; set; }
        public string Unida_Descripcion { get; set; }
        public int Unida_UsuarioCreacion { get; set; }
        public DateTime Unida_FechaCreacion { get; set; }
        public int? Unida_UsuarioModificacion { get; set; }
        public DateTime? Unida_FechaModificacion { get; set; }
        public bool? Unida_Estado { get; set; }

        public virtual tbUsuarios Unida_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Unida_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbComprasDetalle> tbComprasDetalle { get; set; }
        public virtual ICollection<tbProductos> tbProductos { get; set; }
        public virtual ICollection<tbVentasDetalle> tbVentasDetalle { get; set; }
    }
}