// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace InventarioSupermercado.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            InverseUsuar_UsuarioCreacionNavigation = new HashSet<tbUsuarios>();
            InverseUsuar_UsuarioModificacionNavigation = new HashSet<tbUsuarios>();
            tbCargosCargo_UsuarioCreacionNavigation = new HashSet<tbCargos>();
            tbCargosCargo_UsuarioModificacionNavigation = new HashSet<tbCargos>();
            tbCategoriasCateg_UsuarioCreacionNavigation = new HashSet<tbCategorias>();
            tbCategoriasCateg_UsuarioModificacionNavigation = new HashSet<tbCategorias>();
            tbComprasDetalleComde_UsuarioCreacionNavigation = new HashSet<tbComprasDetalle>();
            tbComprasDetalleComde_UsuarioModificacionNavigation = new HashSet<tbComprasDetalle>();
            tbComprasEncabezadoComen_UsuarioCreacionNavigation = new HashSet<tbComprasEncabezado>();
            tbComprasEncabezadoComen_UsuarioModificacionNavigation = new HashSet<tbComprasEncabezado>();
            tbDepartamentosDepar_UsuarioCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosDepar_UsuarioModificacionNavigation = new HashSet<tbDepartamentos>();
            tbEmpleadosEmple_UsuarioCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosEmple_UsuarioModificacionNavigation = new HashSet<tbEmpleados>();
            tbEstadosCivilesEstad_UsuarioCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesEstad_UsuarioModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbImpuestosImpue_UsuarioCreacionNavigation = new HashSet<tbImpuestos>();
            tbImpuestosImpue_UsuarioModificacionNavigation = new HashSet<tbImpuestos>();
            tbMunicipiosMunic_UsuarioCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosMunic_UsuarioModificacionNavigation = new HashSet<tbMunicipios>();
            tbPantallasPanta_UsuarioCreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPanta_UsuarioModificacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPorRolesPapro_UsuarioCreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesPapro_UsuarioModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbProductosProdu_UsuarioCreacionNavigation = new HashSet<tbProductos>();
            tbProductosProdu_UsuarioModificacionNavigation = new HashSet<tbProductos>();
            tbProveedoresProve_UsuarioCreacionNavigation = new HashSet<tbProveedores>();
            tbProveedoresProve_UsuarioModificacionNavigation = new HashSet<tbProveedores>();
            tbRolesRoles_UsuarioCreacionNavigation = new HashSet<tbRoles>();
            tbRolesRoles_UsuarioModificacionNavigation = new HashSet<tbRoles>();
            tbSucursalesSucur_UsuarioCreacionNavigation = new HashSet<tbSucursales>();
            tbSucursalesSucur_UsuarioModificacionNavigation = new HashSet<tbSucursales>();
            tbUnidadesUnida_UsuarioCreacionNavigation = new HashSet<tbUnidades>();
            tbUnidadesUnida_UsuarioModificacionNavigation = new HashSet<tbUnidades>();
            tbVentasDetalleVende_UsuarioCreacionNavigation = new HashSet<tbVentasDetalle>();
            tbVentasDetalleVende_UsuarioModificacionNavigation = new HashSet<tbVentasDetalle>();
            tbVentasEncabezadoVenen_UsuarioCreacionNavigation = new HashSet<tbVentasEncabezado>();
            tbVentasEncabezadoVenen_UsuarioModificacionNavigation = new HashSet<tbVentasEncabezado>();
        }

        public int Usuar_Id { get; set; }
        public string Usuar_Usuario { get; set; }
        public string Usuar_Contrasena { get; set; }
        public int Emple_Id { get; set; }
        public int Roles_Id { get; set; }
        public int Perso_Id { get; set; }
        public bool Usuar_Tipo { get; set; }


        public bool Usuar_Admin { get; set; }

        public DateTime? Usuar_UltimaSesion { get; set; }
        public int Usuar_UsuarioCreacion { get; set; }
        public DateTime Usuar_FechaCreacion { get; set; }
        public int? Usuar_UsuarioModificacion { get; set; }
        public DateTime? Usuar_FechaModificacion { get; set; }
        public bool? Usuar_Estado { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModificacion { get; set; }
        [NotMapped]
        public string empleado { get; set; }
        [NotMapped]
        public string Roles_Descripcion { get; set; }
        [NotMapped]

        public string Perso_NombreCompleto { get; set; }


        public virtual tbEmpleados Emple { get; set; }
        public virtual tbRoles Roles { get; set; }
        public virtual tbUsuarios Usuar_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Usuar_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsuar_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsuar_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargosCargo_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargosCargo_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriasCateg_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriasCateg_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbComprasDetalle> tbComprasDetalleComde_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbComprasDetalle> tbComprasDetalleComde_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbComprasEncabezado> tbComprasEncabezadoComen_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbComprasEncabezado> tbComprasEncabezadoComen_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosDepar_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosDepar_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosEmple_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosEmple_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEstad_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEstad_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbImpuestos> tbImpuestosImpue_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbImpuestos> tbImpuestosImpue_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosMunic_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosMunic_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPanta_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPanta_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPapro_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPapro_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductosProdu_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductosProdu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresProve_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresProve_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRoles_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRoles_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalesSucur_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalesSucur_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbUnidades> tbUnidadesUnida_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbUnidades> tbUnidadesUnida_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbVentasDetalle> tbVentasDetalleVende_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbVentasDetalle> tbVentasDetalleVende_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbVentasEncabezado> tbVentasEncabezadoVenen_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbVentasEncabezado> tbVentasEncabezadoVenen_UsuarioModificacionNavigation { get; set; }
    }
}